name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - run: cargo build
      - run: cargo test --features serde
      - run: cargo fmt --all -- --check
      - run: cargo clippy
